/**
 * YouTube Ingestion Service Configuration
 */

export const config = {
  // Service settings
  port: process.env.PORT || 8080,

  // Redis configuration
  redis: {
    host: process.env.REDIS_HOST || 'redis-queue.cortex.svc.cluster.local',
    port: process.env.REDIS_PORT || 6379,
    enabled: process.env.REDIS_ENABLED !== 'false'
  },

  // Queue names
  queues: {
    ingestion: 'youtube:ingestion',
    processing: 'youtube:processing',
    improvement: 'youtube:improvement'
  },

  // Storage configuration
  storage: {
    transcriptsDir: process.env.TRANSCRIPTS_DIR || '/data/transcripts',
    knowledgeDir: process.env.KNOWLEDGE_DIR || '/data/knowledge',
    cacheDir: process.env.CACHE_DIR || '/data/cache'
  },

  // Anthropic API
  anthropic: {
    apiKey: process.env.ANTHROPIC_API_KEY,
    model: process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-5-20250929',
    maxTokens: 4096
  },

  // URL patterns for detection
  urlPatterns: [
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/,
    /(?:https?:\/\/)?(?:www\.)?youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/live\/([a-zA-Z0-9_-]{11})/
  ],

  // Classification categories
  categories: [
    'tutorial',
    'architecture',
    'concept',
    'tool-demo',
    'discussion',
    'code-walkthrough',
    'conference-talk',
    'lecture',
    'review',
    'other'
  ],

  // Transcript extraction settings
  extraction: {
    preferredLanguages: ['en'],
    fallbackToAutoGenerated: true,
    includeTimestamps: true,
    maxRetries: 3,
    retryDelay: 2000
  },

  // Self-improvement thresholds
  improvement: {
    minRelevanceScore: 0.6,
    autoApproveThreshold: 0.9,
    reviewIntervalHours: 24,
    minVideosForPattern: 3
  },

  // Cache settings
  cache: {
    transcriptTTL: 30 * 24 * 60 * 60, // 30 days in seconds
    videoMetadataTTL: 7 * 24 * 60 * 60, // 7 days
    cleanupIntervalHours: 6
  }
};

export default config;
