apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-queue-pvc
  namespace: cortex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
