apiVersion: v1
kind: Service
metadata:
  name: redis-queue
  namespace: cortex
  labels:
    app: redis-queue
    component: task-queue
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis-queue
