apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-tasks-pvc
  namespace: cortex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
