---
# ConfigMap for rsyslog configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-unifi-config
  namespace: default
data:
  rsyslog.conf: |
    # Load modules
    module(load="imudp")
    module(load="imtcp")

    # UDP syslog reception on port 514
    input(type="imudp" port="514")

    # TCP syslog reception on port 514
    input(type="imtcp" port="514")

    # Template for UniFi logs
    template(name="UniFiLogFile" type="string" string="/var/log/unifi/%HOSTNAME%_%$YEAR%%$MONTH%%$DAY%.log")
    template(name="UniFiLogFormat" type="string" string="%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")

    # Route ALL UniFi logs to dedicated directory and Wazuh
    # Matches: Dream-Machine-Pro, U6-Plus, U7-Pro, and any UniFi device
    if ($fromhost-ip startswith '10.88.140.' or $hostname contains 'Dream-Machine' or $hostname contains 'U6' or $hostname contains 'U7' or $hostname contains 'USW' or $msg contains 'UniFi') then {
      action(type="omfile" dynaFile="UniFiLogFile" template="UniFiLogFormat")

      # Forward to Wazuh manager syslog port
      action(type="omfwd" target="wazuh-manager.wazuh-security.svc.cluster.local" port="514" protocol="udp")
    }

    # Also forward everything to Wazuh for analysis
    *.* action(type="omfwd" target="wazuh-manager.wazuh-security.svc.cluster.local" port="514" protocol="udp")

    # Default logging
    *.info;mail.none;authpriv.none;cron.none /var/log/messages
    authpriv.* /var/log/secure
    mail.* -/var/log/maillog
    cron.* /var/log/cron
    *.emerg :omusrmsg:*
    uucp,news.crit /var/log/spooler
    local7.* /var/log/boot.log
---
# Deployment for UniFi syslog receiver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-syslog-receiver
  namespace: default
  labels:
    app: unifi-syslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-syslog
  template:
    metadata:
      labels:
        app: unifi-syslog
    spec:
      containers:
      - name: rsyslog
        image: rsyslog/syslog_appliance_alpine:latest
        ports:
        - containerPort: 514
          protocol: UDP
          name: syslog-udp
        - containerPort: 514
          protocol: TCP
          name: syslog-tcp
        volumeMounts:
        - name: config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: logs
          mountPath: /var/log/unifi
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: rsyslog-unifi-config
      - name: logs
        emptyDir: {}
---
# Service for syslog receiver with LoadBalancer on 10.88.145.208
apiVersion: v1
kind: Service
metadata:
  name: unifi-syslog
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.88.145.215
spec:
  type: LoadBalancer
  ports:
  - name: syslog-udp
    port: 514
    targetPort: 514
    protocol: UDP
  - name: syslog-tcp
    port: 514
    targetPort: 514
    protocol: TCP
  selector:
    app: unifi-syslog
