apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"release":"kube-prometheus-stack"},"name":"cloudflare-exporter","namespace":"monitoring-exporters"},"spec":{"endpoints":[{"interval":"60s","port":"metrics"}],"selector":{"matchLabels":{"app":"cloudflare-exporter"}}}}
  labels:
    release: kube-prometheus-stack
  name: cloudflare-exporter
  namespace: monitoring-exporters
spec:
  endpoints:
  - interval: 60s
    port: metrics
  selector:
    matchLabels:
      app: cloudflare-exporter
