apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cloudflare-exporter"},"name":"cloudflare-exporter","namespace":"monitoring-exporters"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"cloudflare-exporter"}},"template":{"metadata":{"labels":{"app":"cloudflare-exporter"}},"spec":{"containers":[{"env":[{"name":"CF_API_KEY","valueFrom":{"secretKeyRef":{"key":"CF_API_KEY","name":"cloudflare-exporter-credentials"}}},{"name":"CF_API_EMAIL","valueFrom":{"secretKeyRef":{"key":"CF_API_EMAIL","name":"cloudflare-exporter-credentials"}}}],"image":"lablabs/cloudflare_exporter:latest","name":"exporter","ports":[{"containerPort":8080,"name":"metrics"}],"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}]}}}}
  labels:
    app: cloudflare-exporter
  name: cloudflare-exporter
  namespace: monitoring-exporters
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cloudflare-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-21T18:48:33-06:00"
      labels:
        app: cloudflare-exporter
    spec:
      containers:
      - env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: CF_API_TOKEN
              name: cloudflare-exporter-credentials
        image: ghcr.io/lablabs/cloudflare_exporter:latest
        imagePullPolicy: Always
        name: exporter
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-22T00:48:36Z"
    lastUpdateTime: "2025-12-22T00:48:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-22T00:43:52Z"
    lastUpdateTime: "2025-12-22T00:48:36Z"
    message: ReplicaSet "cloudflare-exporter-54d74b5bf4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
