apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"proxmox-exporter"},"name":"proxmox-exporter","namespace":"monitoring-exporters"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"proxmox-exporter"}},"template":{"metadata":{"labels":{"app":"proxmox-exporter"}},"spec":{"containers":[{"args":["--collector.status","--collector.version","--collector.node","--collector.cluster","--collector.resources","--collector.config"],"env":[{"name":"PVE_USER","valueFrom":{"secretKeyRef":{"key":"PROXMOX_USER","name":"proxmox-exporter-credentials"}}},{"name":"PVE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"PROXMOX_PASSWORD","name":"proxmox-exporter-credentials"}}},{"name":"PVE_VERIFY_SSL","valueFrom":{"secretKeyRef":{"key":"PROXMOX_VERIFY_SSL","name":"proxmox-exporter-credentials"}}}],"image":"prompve/prometheus-pve-exporter:latest","name":"exporter","ports":[{"containerPort":9221,"name":"metrics"}],"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  labels:
    app: proxmox-exporter
  name: proxmox-exporter
  namespace: monitoring-exporters
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: proxmox-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-21T18:40:34-06:00"
      labels:
        app: proxmox-exporter
    spec:
      containers:
      - args:
        - --collector.status
        - --collector.version
        - --collector.node
        - --collector.cluster
        - --collector.resources
        - --collector.config
        - --collector.qemu
        - --collector.lxc
        image: prompve/prometheus-pve-exporter:latest
        imagePullPolicy: Always
        name: exporter
        ports:
        - containerPort: 9221
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: proxmox-exporter-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-21T22:43:18Z"
    lastUpdateTime: "2025-12-21T22:43:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-21T00:48:38Z"
    lastUpdateTime: "2025-12-22T00:40:38Z"
    message: ReplicaSet "proxmox-exporter-7c9f49ddf7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
