apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"release":"kube-prometheus-stack"},"name":"redis-exporter","namespace":"monitoring-exporters"},"spec":{"endpoints":[{"interval":"30s","port":"metrics"}],"selector":{"matchLabels":{"app":"redis-exporter"}}}}
  labels:
    release: kube-prometheus-stack
  name: redis-exporter
  namespace: monitoring-exporters
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: redis-exporter
