apiVersion: v1
kind: Service
metadata:
  name: documentation-master
  namespace: cortex
  labels:
    app: documentation-master
    cortex-role: master
spec:
  selector:
    app: documentation-master
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
  sessionAffinity: ClientIP
