apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documentation-kb-pvc
  namespace: cortex
  labels:
    app: documentation-master
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documentation-cache-pvc
  namespace: cortex
  labels:
    app: documentation-master
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
